-- Add extra customer fields
ALTER TABLE customers ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS area VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tier VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shop_type VARCHAR(100);

UPDATE customers SET phone='0777547048', area='BADULLA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MILLENIYAM LOVERS';
UPDATE customers SET phone='0771804411', area='BADULLA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='SHAHARA FANCY MAHAI';
UPDATE customers SET phone='0759991919', area='BADULLA 02', tier='Silver', shop_type='Shoe Shop' WHERE name='SHOE PARK';
UPDATE customers SET phone='0773216160', area='BADULLA 02', tier='Gold', shop_type='Bag Shop' WHERE name='I AM YOURS';
UPDATE customers SET phone='0763320656', area='BADULLA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='MASHA TEX';
UPDATE customers SET phone='0775635421', area='BADULLA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HAPPY KIDS';
UPDATE customers SET phone='0775344680', area='BADULLA 02', tier='Silver', shop_type='Book Shop and Communication' WHERE name='MAHINDAS BOOK CENTER';
UPDATE customers SET phone='0754836486', area='BADULLA 02', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='DEEN FANCY HOUSE';
UPDATE customers SET phone='0776111685', area='BADULLA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='G.K.P.FASHION';
UPDATE customers SET phone='0772544722', area='BADULLA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='MOM AND BABY';
UPDATE customers SET phone='0779809462', area='BADULLA 02', tier='Emergency Top-up', shop_type='Multi Outlet' WHERE name='DAMIANS ENTERPRICES';
UPDATE customers SET phone='0773143695', area='BADULLA 02', tier='Silver', shop_type='Mother/Baby Care Outlet' WHERE name='KAILASH FASHION';
UPDATE customers SET phone='0778789935', area='BADULLA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='ARUN TAILORS';
UPDATE customers SET phone='0767593908', area='BADULLA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MY LADDY';
UPDATE customers SET phone='0552231698', area='BADULLA 02', tier='Silver', shop_type='Multi Outlet' WHERE name='RAFEIQUES ELECTHONICS';
UPDATE customers SET phone='0763133767', area='BADULLA 02', tier='Bronze', shop_type='Multi Outlet' WHERE name='H.A.BAGASRAWAIA AND SONS';
UPDATE customers SET phone='N/A', area='BADULLA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='LUXMI FANCY';
UPDATE customers SET phone='0779783634', area='BADULLA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='LOVERS DREAMS';
UPDATE customers SET phone='0552228858', area='BADULLA 02', tier='Silver', shop_type='Fancy Outlet' WHERE name='PURPLE';
UPDATE customers SET phone='0552229919', area='BADULLA 02', tier='Platinum', shop_type='Cosmetic and Fancy Outlet' WHERE name='NOVIA';
UPDATE customers SET phone='0552222502', area='BADULLA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='LIMA FASHION';
UPDATE customers SET phone='0552234196', area='BADULLA 03', tier='Silver', shop_type='Pooja Banda Outlet' WHERE name='CHANDANA POOJA BANDA';
UPDATE customers SET phone='0771234536', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='BARAKATH TEXTILE';
UPDATE customers SET phone='0773135010', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HEMA TEX';
UPDATE customers SET phone='0775045010', area='BADULLA 03', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='INDIYAN FANCY';
UPDATE customers SET phone='0715531610', area='BADULLA 03', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='ASOK FANCY';
UPDATE customers SET phone='0723657614', area='BADULLA 03', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='SARAVANAS';
UPDATE customers SET phone='0552223688', area='BADULLA 03', tier='Silver', shop_type='Textile and Fashion' WHERE name='R.L.G.FASHION';
UPDATE customers SET phone='0552224609', area='BADULLA 03', tier='Silver', shop_type='Book Shop and Communication' WHERE name='RIO COMMUNI CATION';
UPDATE customers SET phone='0729611396', area='BADULLA 03', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='BADULLA SALES';
UPDATE customers SET phone='0776524005', area='BADULLA 03', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='H.N.AGENCY';
UPDATE customers SET phone='0773548659', area='BADULLA 03', tier='Bronze', shop_type='Super Market' WHERE name='KARUNARATHNA SUPER AND COMMIUNICATION';
UPDATE customers SET phone='0714209635', area='BADULLA 03', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SANROW TEX';
UPDATE customers SET phone='0777707758', area='BADULLA 03', tier='Gold', shop_type='Textile and Fashion' WHERE name='ANGEL LOVERS';
UPDATE customers SET phone='0779905830', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MAHINDA BOOK SHOP';
UPDATE customers SET phone='0724606804', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='REEHA FASHION TEX';
UPDATE customers SET phone='0779061908', area='BADULLA 03', tier='Silver', shop_type='Textile and Fashion' WHERE name='CENTERPOINT';
UPDATE customers SET phone='0758181301', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='S.J.FASHION';
UPDATE customers SET phone='0774638319', area='BADULLA 03', tier='Bronze', shop_type='Grocery' WHERE name='MILANO GROCERY';
UPDATE customers SET phone='0771799159', area='BADULLA 03', tier='Bronze', shop_type='Grocery' WHERE name='H.A.TREDRES';
UPDATE customers SET phone='0719298261', area='BADULLA 03', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='GANGADISI COMMUNI';
UPDATE customers SET phone='0778660215', area='BADULLA 03', tier='Gold', shop_type='Textile and Fashion' WHERE name='KAMARZIAS';
UPDATE customers SET phone='0761195181', area='BADULLA 03', tier='Bronze', shop_type='Multi Outlet' WHERE name='PIYAKARU MULTI TRAINING';
UPDATE customers SET phone='0710342542', area='BADULLA 03', tier='Bronze', shop_type='Shoe Shop' WHERE name='S.L.T SHOE';
UPDATE customers SET phone='0741099692', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HALI ELA GOLD HOUSE AND MEGA MARTS';
UPDATE customers SET phone='0773702740', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='S.A.FASHION';
UPDATE customers SET phone='0770855108', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='METRO FANCY';
UPDATE customers SET phone='0787666978', area='BADULLA 03', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='SRI WIJAYA POOJA BANDA';
UPDATE customers SET phone='0763806588', area='BADULLA 03', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='VASI FANCY';
UPDATE customers SET phone='0777746762', area='BADULLA 03', tier='Platinum', shop_type='Shoe Shop' WHERE name='DSI FASHION SHOE';
UPDATE customers SET phone='0768704233', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RICH LOOK';
UPDATE customers SET phone='0778140706', area='BADULLA 03', tier='Bronze', shop_type='Textile and Fashion' WHERE name='KALA TAILORS AND TEXTILE';
UPDATE customers SET phone='0552248795', area='BADULLA 03', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='ACME SCHOOL AND OFFICE SUPPLIER ( PVT) LTD.';
UPDATE customers SET phone='0783140833', area='BADULLA 03', tier='Silver', shop_type='Super Market' WHERE name='UDARA';
UPDATE customers SET phone='0777912034', area='BADULLA 01', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='VISVAMS';
UPDATE customers SET phone='0552223020', area='BADULLA 01', tier='Silver', shop_type='Bag Shop' WHERE name='BARAKATH TREDES';
UPDATE customers SET phone='0777926804', area='BADULLA 01', tier='Platinum', shop_type='Cosmetic and Fancy Outlet' WHERE name='FANCY PARK';
UPDATE customers SET phone='0703511352', area='BADULLA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='MUMMY DADY';
UPDATE customers SET phone='0772833188', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='S.S.B.TEX';
UPDATE customers SET phone='0779006636', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='LUCKY PARADICE';
UPDATE customers SET phone='0775702246', area='BADULLA 01', tier='Silver', shop_type='Bag Shop' WHERE name='SAMANALA ENTERPRISES';
UPDATE customers SET phone='0773074655', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='DHEVI FANCY';
UPDATE customers SET phone='0779302096', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='FAIR LANKA';
UPDATE customers SET phone='0777656045', area='BADULLA 01', tier='Gold', shop_type='Pooja Banda Outlet' WHERE name='WIJESOORIYA AND SONS';
UPDATE customers SET phone='0712418710', area='BADULLA 01', tier='Gold', shop_type='Pooja Banda Outlet' WHERE name='SILVA DAPARY';
UPDATE customers SET phone='0552229250', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='AL FATHAH EMPORIUM';
UPDATE customers SET phone='0779329060', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='ASHAN TEX';
UPDATE customers SET phone='0773625011', area='BADULLA 01', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='QUEENS PALECE';
UPDATE customers SET phone='0774525219', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='JAMEELS';
UPDATE customers SET phone='0777073770', area='BADULLA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='SAMANALA BOOK SHOP';
UPDATE customers SET phone='0775623145', area='BADULLA 01', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='NANDA STORES';
UPDATE customers SET phone='0777384922', area='BADULLA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW NANDA STOERS';
UPDATE customers SET phone='0771290400', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='BIG C';
UPDATE customers SET phone='0777781872', area='BADULLA 01', tier='Gold', shop_type='Shoe Shop' WHERE name='NEW SHOE KINGDOM';
UPDATE customers SET phone='0772835180', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='SAFAYAS';
UPDATE customers SET phone='0714209635', area='BADULLA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SANROW TEX';
UPDATE customers SET phone='0775685125', area='BADULLA 01', tier='Silver', shop_type='Super Market' WHERE name='M.K.B.SUPER CITY';
UPDATE customers SET phone='0777784027', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='30 KADE';
UPDATE customers SET phone='0775797800', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='THAHEER FANCY';
UPDATE customers SET phone='0777926804', area='BADULLA 01', tier='Platinum', shop_type='Cosmetic and Fancy Outlet' WHERE name='GHANIM ENTERPRICES';
UPDATE customers SET phone='0776929178', area='BADULLA 01', tier='Gold', shop_type='Mother/Baby Care Outlet' WHERE name='VISVAMS TRADERS';
UPDATE customers SET phone='0552223394', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='SHAP CORNER';
UPDATE customers SET phone='0552224680', area='BADULLA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='UDAYA BOOK SHOP';
UPDATE customers SET phone='0552235186', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SOBA TEX';
UPDATE customers SET phone='0552225872', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MOHAMEDIYAS';
UPDATE customers SET phone='0770752976', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='KUMARANS TEX';
UPDATE customers SET phone='0767461433', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHALOM';
UPDATE customers SET phone='0777912034', area='BADULLA 01', tier='Silver', shop_type='Mother/Baby Care Outlet' WHERE name='BABY BAZZR';
UPDATE customers SET phone='0768086886', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='BISMI';
UPDATE customers SET phone='0552220022', area='BADULLA 01', tier='Silver', shop_type='Super Market' WHERE name='M.K.B BADULLA (PVT)LTD';
UPDATE customers SET phone='0774238181', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HI LOOK';
UPDATE customers SET phone='0774047672', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='DEWLI TEXTILE';
UPDATE customers SET phone='0778540575', area='BADULLA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='AMAANS';
UPDATE customers SET phone='0777382301', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MARLIYAS';
UPDATE customers SET phone='0787666978', area='BADULLA 01', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='SRI WIJAYA POOJA BANDA';
UPDATE customers SET phone='0773202682', area='BADULLA 01', tier='Silver', shop_type='Pooja Banda Outlet' WHERE name='UD SATERLITE SYSTEMS';
UPDATE customers SET phone='0552229191', area='BADULLA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='Dehipe Enterprises';
UPDATE customers SET phone='0776703920', area='BADULLA 01', tier='Bronze', shop_type='Fancy Outlet' WHERE name='BISMI 100 / KADE';
UPDATE customers SET phone='0777123440', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='TBL FASHION';
UPDATE customers SET phone='0759991919', area='BADULLA 01', tier='Silver', shop_type='Shoe Shop' WHERE name='SHOE PARK';
UPDATE customers SET phone='0773216160', area='BADULLA 01', tier='Gold', shop_type='Bag Shop' WHERE name='I AM YOURS';
UPDATE customers SET phone='0763320656', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='MASHA TEX';
UPDATE customers SET phone='0775635421', area='BADULLA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HAPPY KIDS';
UPDATE customers SET phone='0775344680', area='BADULLA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='MAHINDAS BOOK CENTER';
UPDATE customers SET phone='0776111685', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='G.K.P.FASHION';
UPDATE customers SET phone='0772544722', area='BADULLA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='MOM AND BABY';
UPDATE customers SET phone='0779809462', area='BADULLA 01', tier='Emergency Top-up', shop_type='Multi Outlet' WHERE name='DAMIANS ENTERPRICES';
UPDATE customers SET phone='0767593908', area='BADULLA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MY LADDY';
UPDATE customers SET phone='0552231698', area='BADULLA 01', tier='Silver', shop_type='Multi Outlet' WHERE name='RAFEIQUES ELECTHONICS';
UPDATE customers SET phone='0763133767', area='BADULLA 01', tier='Bronze', shop_type='Multi Outlet' WHERE name='H.A.BAGASRAWAIA AND SONS';
UPDATE customers SET phone='0552229919', area='BADULLA 01', tier='Platinum', shop_type='Cosmetic and Fancy Outlet' WHERE name='NOVIA';
UPDATE customers SET phone='0764940939', area='BADALKUMBURA', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='JAREENAS PLUS';
UPDATE customers SET phone='0776002565', area='BADALKUMBURA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='FINGERS';
UPDATE customers SET phone='0776508119', area='BADALKUMBURA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='NUSKI FANCY CHOICE';
UPDATE customers SET phone='0767427878', area='BADALKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='OSHEL';
UPDATE customers SET phone='0716218813', area='BADALKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='DILORA TEX';
UPDATE customers SET phone='0775624135', area='BADALKUMBURA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='NIMACO MULTY CARE';
UPDATE customers SET phone='0772242718', area='BADALKUMBURA', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='STAR FURNITURE';
UPDATE customers SET phone='0759070907', area='BADALKUMBURA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='LOVER DIHANSHA';
UPDATE customers SET phone='0772064096', area='BADALKUMBURA', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='AMILA POOJA BANDA';
UPDATE customers SET phone='0717285366', area='BADALKUMBURA', tier='Silver', shop_type='Pooja Banda Outlet' WHERE name='JAYASRI POOJA';
UPDATE customers SET phone='0754618586', area='BADALKUMBURA', tier='Silver', shop_type='Textile and Fashion' WHERE name='BEUTY FASHION';
UPDATE customers SET phone='0775444216', area='BADALKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FANCY BAZAAR';
UPDATE customers SET phone='0710801140', area='BADALKUMBURA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='KANDY BOOK SHOP';
UPDATE customers SET phone='0774075484', area='BADALKUMBURA', tier='Silver', shop_type='Shoe Shop' WHERE name='MONARA SHOE PALACE';
UPDATE customers SET phone='0777832794', area='BADALKUMBURA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='J.SILMY';
UPDATE customers SET phone='0778651559', area='BADALKUMBURA', tier='Bronze', shop_type='Shoe Shop' WHERE name='APPOLO SHOE PALECE';
UPDATE customers SET phone='N/A', area='BADALKUMBURA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='FANCY POINT';
UPDATE customers SET phone='0775303917', area='BADALKUMBURA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='CITY POINT';
UPDATE customers SET phone='0772165350', area='BADALKUMBURA', tier='Platinum', shop_type='Fancy Outlet' WHERE name='N S  FANCY';
UPDATE customers SET phone='0777174374', area='BANDARAWELA 01', tier='Gold', shop_type='Textile and Fashion' WHERE name='KALEEMA EMPORIUM';
UPDATE customers SET phone='0771834995', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='ANUSHA TEXTILES';
UPDATE customers SET phone='0779134030', area='BANDARAWELA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MANDARA TEXTILE';
UPDATE customers SET phone='0777591349', area='BANDARAWELA 01', tier='Platinum', shop_type='Textile and Fashion' WHERE name='JANALANKA TEXTILE';
UPDATE customers SET phone='0767171010', area='BANDARAWELA 01', tier='Bronze', shop_type='Shoe Shop' WHERE name='NEW FASHION SHOE PALACE';
UPDATE customers SET phone='0778111859', area='BANDARAWELA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='FANCY MAHAL';
UPDATE customers SET phone='0775740373', area='BANDARAWELA 01', tier='Silver', shop_type='Grocery' WHERE name='KUMARAN TRADING';
UPDATE customers SET phone='0572222197', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='SUBASS TEX';
UPDATE customers SET phone='0764087859', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='NEW YOUR CHOICE';
UPDATE customers SET phone='0713251411', area='BANDARAWELA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='SRI ENTERPRISE';
UPDATE customers SET phone='0572220666', area='BANDARAWELA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='MARUTHY FANCY';
UPDATE customers SET phone='0572233466', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='GAYANS TEXTILE (PVT)LTD';
UPDATE customers SET phone='0773208544', area='BANDARAWELA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='GUNASIRI TEXTILE';
UPDATE customers SET phone='0774179058', area='BANDARAWELA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='THULANI FANCY';
UPDATE customers SET phone='0771114495', area='BANDARAWELA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='LANKA CITY CENTER';
UPDATE customers SET phone='0777779612', area='BANDARAWELA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FASHON HOUSE';
UPDATE customers SET phone='0777446296', area='BANDARAWELA 01', tier='Emergency Top-up', shop_type='Cosmetic and Fancy Outlet' WHERE name='HATHIYA FANCY';
UPDATE customers SET phone='0777408999', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='NAVA LADY  FASHION';
UPDATE customers SET phone='0773712432', area='BANDARAWELA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='HILL TOP SELECTION';
UPDATE customers SET phone='0777585396', area='BANDARAWELA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='STAR KINDOM FANCY HOUSE';
UPDATE customers SET phone='0772848433', area='BANDARAWELA 01', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='HAPPY HOME';
UPDATE customers SET phone='0778081666', area='BANDARAWELA 01', tier='Silver', shop_type='Book Shop and Communication' WHERE name='CITY BOOK SHOP';
UPDATE customers SET phone='0756816091', area='BANDARAWELA 01', tier='Emergency Top-up', shop_type='Bag Shop' WHERE name='SALE CENTRE';
UPDATE customers SET phone='0771290400', area='BANDARAWELA 01', tier='Silver', shop_type='Multi Outlet' WHERE name='LOVER BIG C';
UPDATE customers SET phone='0773780010', area='BANDARAWELA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='J.ROOS';
UPDATE customers SET phone='0728005200', area='BANDARAWELA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='DARWIN';
UPDATE customers SET phone='0776320844', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='SUBAS TEXTILE AND TAILORS';
UPDATE customers SET phone='0723314692', area='BANDARAWELA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='FASHION LANKA';
UPDATE customers SET phone='0772281394', area='BANDARAWELA 01', tier='Bronze', shop_type='Grocery' WHERE name='LEELASENA STORES';
UPDATE customers SET phone='0765575000', area='BANDARAWELA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='PRASANNA TEXTILE';
UPDATE customers SET phone='0710758102', area='BANDARAWELA 01', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='SARASAVIYA';
UPDATE customers SET phone='0724783380', area='BANDARAWELA 02', tier='Silver', shop_type='Mother/Baby Care Outlet' WHERE name='BABY KINGDOM';
UPDATE customers SET phone='0702373709', area='BANDARAWELA 02', tier='Bronze', shop_type='Shoe Shop' WHERE name='AWIDIMU D S I';
UPDATE customers SET phone='0775623124', area='BANDARAWELA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SRI JAYA BOOK SHOP';
UPDATE customers SET phone='0716997729', area='BANDARAWELA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='RIFAS TEXTILE';
UPDATE customers SET phone='0770882934', area='BANDARAWELA 02', tier='Bronze', shop_type='Shoe Shop' WHERE name='RATHNAYAKE SHOES';
UPDATE customers SET phone='0768299612', area='BANDARAWELA 02', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='TAINY TEX';
UPDATE customers SET phone='0552234194', area='BANDARAWELA 02', tier='Bronze', shop_type='Multi Outlet' WHERE name='H.M.KIRIWANTHE AND SONS';
UPDATE customers SET phone='0775624187', area='BANDARAWELA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SIVAS FANCY HOUSE';
UPDATE customers SET phone='0775645235', area='BANDARAWELA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NEW HI-STYLE';
UPDATE customers SET phone='0715863952', area='BANDARAWELA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='KRYSTAL';
UPDATE customers SET phone='0778167729', area='BANDARAWELA 02', tier='Bronze', shop_type='Shoe Shop' WHERE name='NEAON SHOE MART';
UPDATE customers SET phone='0767562750', area='BANDARAWELA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='MAHAJANE TEXTILE';
UPDATE customers SET phone='0760606752', area='BANDARAWELA 02', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='LOVER GLAMOUR CITY';
UPDATE customers SET phone='0773780010', area='BANDARAWELA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='J.ROOS';
UPDATE customers SET phone='0772224240', area='BANDARAWELA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SAMANAL';
UPDATE customers SET phone='0572228810', area='BANDARAWELA 02', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='SENA FURNITURE';
UPDATE customers SET phone='0572235357', area='BANDARAWELA 02', tier='Silver', shop_type='Super Market' WHERE name='CLEAR POINT SUPER AND CAFE';
UPDATE customers SET phone='0773075878', area='BANDARAWELA 02', tier='Gold', shop_type='Textile and Fashion' WHERE name='JENITAS';
UPDATE customers SET phone='0774628535', area='BANDARAWELA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='C N E';
UPDATE customers SET phone='0761448148', area='BANDARAWELA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='PC FANCY';
UPDATE customers SET phone='0776758711', area='BANDARAWELA 02', tier='Silver', shop_type='Grocery' WHERE name='CK SUPERMART';
UPDATE customers SET phone='0712994429', area='BANDARAWELA 02', tier='Silver', shop_type='Mother/Baby Care Outlet' WHERE name='HELLO BABY';
UPDATE customers SET phone='0778056457', area='BANDARAWELA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NIMAL TEXTILE';
UPDATE customers SET phone='0766064674', area='BANDARAWELA 02', tier='Platinum', shop_type='Fancy Outlet' WHERE name='LAKSHI FANCY AND NEW LANKA SALON';
UPDATE customers SET phone='0572228527', area='BANDARAWELA 02', tier='Bronze', shop_type='Grocery' WHERE name='SOMASIRI GROUP OF COMPANIES';
UPDATE customers SET phone='0778502368', area='BANDARAWELA 02', tier='Bronze', shop_type='Fancy Outlet' WHERE name='RENDY GIRLS';
UPDATE customers SET phone='0774082138', area='BANDARAWELA 02', tier='Bronze', shop_type='Shoe Shop' WHERE name='HAYAAN SHOE';
UPDATE customers SET phone='0572225068', area='BANDARAWELA 02', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='IMAGE COMMUNICATION';
UPDATE customers SET phone='0771387934', area='BANDARAWELA 02', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='GOAL BOOK SHOP';
UPDATE customers SET phone='0572280878', area='BOGAHAKUMBURA', tier='Silver', shop_type='Textile and Fashion' WHERE name='WELLAWAYA TAILORS';
UPDATE customers SET phone='0713719336', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Grocery' WHERE name='RAVINDRA TREDES';
UPDATE customers SET phone='0767999090', area='BOGAHAKUMBURA', tier='Silver', shop_type='Shoe Shop' WHERE name='RIZLAN SHOE';
UPDATE customers SET phone='0777870393', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='THEJAN FASHION';
UPDATE customers SET phone='0777053941', area='BOGAHAKUMBURA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='A.C.M.FANCY HOUSE';
UPDATE customers SET phone='0754235112', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='AJANTHA SUPER COLLECTION';
UPDATE customers SET phone='0718166317', area='BOGAHAKUMBURA', tier='Silver', shop_type='Textile and Fashion' WHERE name='MANJULA TEX';
UPDATE customers SET phone='0772277687', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='LAKSHIKA BOOK CENTER';
UPDATE customers SET phone='0740843645', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SOMASIRI GIFT';
UPDATE customers SET phone='0572281394', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RAMYA TEX';
UPDATE customers SET phone='0777353936', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='YOGAS TEXTILE';
UPDATE customers SET phone='0762876483', area='BOGAHAKUMBURA', tier='Silver', shop_type='Textile and Fashion' WHERE name='NEW FASHION TEXTILE';
UPDATE customers SET phone='0773229253', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Shoe Shop' WHERE name='PIYAWARA SHOE PALACE';
UPDATE customers SET phone='0716223131', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='D.B.R. Tex';
UPDATE customers SET phone='0777814804', area='BOGAHAKUMBURA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='YOGAS FANCY SHOP';
UPDATE customers SET phone='0723318760', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='AFRA TEX';
UPDATE customers SET phone='0572280142', area='BOGAHAKUMBURA', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='WELLAWAYA STORES';
UPDATE customers SET phone='0774036318', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='PRADEEPA BOOK SHOP';
UPDATE customers SET phone='0714499266', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RANDIRA MANDIRAYA';
UPDATE customers SET phone='0774275779', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MUNAS TEX';
UPDATE customers SET phone='0725069201', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NIMAYA TEXTILE';
UPDATE customers SET phone='0701756865', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SUMUDU TEXTILE';
UPDATE customers SET phone='0711125093', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='THUSHARA BOOK SHOP';
UPDATE customers SET phone='0716995146', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Multi Outlet' WHERE name='RAJAS MULTI SHOP';
UPDATE customers SET phone='0764853248', area='BOGAHAKUMBURA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='RATHNA TALERS AND BOOK SHOP';
UPDATE customers SET phone='0777870393', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NEW THEJAN FASHION';
UPDATE customers SET phone='0778828080', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='RAVI GIFT';
UPDATE customers SET phone='N/A', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RILAYAS';
UPDATE customers SET phone='0779120890', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RAVINDRA TEX AND COMMUNICATION';
UPDATE customers SET phone='0778303612', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Grocery' WHERE name='S.A.K.M.ABDUL RAZAK';
UPDATE customers SET phone='0769125003', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Grocery' WHERE name='HAPPY CHOICES';
UPDATE customers SET phone='0774228724', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='WIJEKA TEXTILE';
UPDATE customers SET phone='0771638564', area='BOGAHAKUMBURA', tier='Platinum', shop_type='Fancy Outlet' WHERE name='DEEN MULTI CENTER';
UPDATE customers SET phone='0712110621', area='BOGAHAKUMBURA', tier='Platinum', shop_type='Fancy Outlet' WHERE name='SOBA SRI PALACE';
UPDATE customers SET phone='0774055886', area='BOGAHAKUMBURA', tier='Bronze', shop_type='Multi Outlet' WHERE name='HUDHA MULTI CHOICE';
UPDATE customers SET phone='0770609503', area='DIYATALAWA', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='TABRUKI CENTER';
UPDATE customers SET phone='0572229266', area='DIYATALAWA', tier='Silver', shop_type='Textile and Fashion' WHERE name='MALSIRI TEXTILE';
UPDATE customers SET phone='0777117877', area='DIYATALAWA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MULTI SHOP';
UPDATE customers SET phone='0716659600', area='DIYATALAWA', tier='Bronze', shop_type='Grocery' WHERE name='PRIYANI STORES';
UPDATE customers SET phone='0711488342', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SETHSIRI TEXTILE';
UPDATE customers SET phone='0777073770', area='DIYATALAWA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='SAMANALA BOOK SHOP';
UPDATE customers SET phone='0771332180', area='DIYATALAWA', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='LESS FASHION';
UPDATE customers SET phone='0718311737', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SITHUMINA FASHION';
UPDATE customers SET phone='0773542158', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHALEEKA TREDE CENTER';
UPDATE customers SET phone='0712021900', area='DIYATALAWA', tier='Gold', shop_type='Fancy Outlet' WHERE name='SUHANDA TAILORS';
UPDATE customers SET phone='0772310772', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MANMANDIR TEX';
UPDATE customers SET phone='0775345233', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='OCHID PALASHA';
UPDATE customers SET phone='0767884553', area='DIYATALAWA', tier='Bronze', shop_type='Multi Outlet' WHERE name='FANCY POINT';
UPDATE customers SET phone='0774350632', area='DIYATALAWA', tier='Bronze', shop_type='Grocery' WHERE name='ISURU SUPER';
UPDATE customers SET phone='0572227276', area='DIYATALAWA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='SABEENA BOOK SHOP';
UPDATE customers SET phone='0702240742', area='DIYATALAWA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='WASANA BABY';
UPDATE customers SET phone='0764090471', area='DIYATALAWA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RAVINDRA TAILORS';
UPDATE customers SET phone='0777075080', area='DIYATALAWA', tier='Bronze', shop_type='Shoe Shop' WHERE name='ACCURATE SHOE';
UPDATE customers SET phone='0761648444', area='DIYATALAWA', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='BISMILLAH HOTEL';
UPDATE customers SET phone='0777433117', area='DIYATALAWA', tier='Emergency Top-up', shop_type='Mother/Baby Care Outlet' WHERE name='SALE KADE';
UPDATE customers SET phone='0714005422', area='DIYATALAWA', tier='Bronze', shop_type='Grocery' WHERE name='CHANNA GROCERY';
UPDATE customers SET phone='0552234196', area='HALI-ELA', tier='Silver', shop_type='Pooja Banda Outlet' WHERE name='CHANDANA POOJA BANDA';
UPDATE customers SET phone='0775245352', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='T.M.P. TEX';
UPDATE customers SET phone='0771234536', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='BARAKATH TEXTILE';
UPDATE customers SET phone='0773135010', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HEMA TEX';
UPDATE customers SET phone='0771234511', area='HALI-ELA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='ASHEEK PANCY';
UPDATE customers SET phone='0775045010', area='HALI-ELA', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='INDIYAN FANCY';
UPDATE customers SET phone='0715531610', area='HALI-ELA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='ASOK FANCY';
UPDATE customers SET phone='0757331620', area='HALI-ELA', tier='Silver', shop_type='Grocery' WHERE name='MADUSHANI SHOE MART';
UPDATE customers SET phone='0552294081', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='DHARSHANA TEXTILE';
UPDATE customers SET phone='0718154246', area='HALI-ELA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='JAYANI MULTI SHOP';
UPDATE customers SET phone='0718179753', area='HALI-ELA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='NAYANA BOOK SHOP';
UPDATE customers SET phone='0773548659', area='HALI-ELA', tier='Bronze', shop_type='Super Market' WHERE name='KARUNARATHNA SUPER AND COMMIUNICATION';
UPDATE customers SET phone='0724606804', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='REEHA FASHION TEX';
UPDATE customers SET phone='0777349652', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHAN FASHION';
UPDATE customers SET phone='0779061908', area='HALI-ELA', tier='Silver', shop_type='Textile and Fashion' WHERE name='CENTERPOINT';
UPDATE customers SET phone='0758181301', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='S.J.FASHION';
UPDATE customers SET phone='0719298261', area='HALI-ELA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='GANGADISI COMMUNI';
UPDATE customers SET phone='0552295036', area='HALI-ELA', tier='Bronze', shop_type='Grocery' WHERE name='GALLEGE STORES';
UPDATE customers SET phone='0710342542', area='HALI-ELA', tier='Bronze', shop_type='Shoe Shop' WHERE name='S.L.T SHOE';
UPDATE customers SET phone='0741099692', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='HALI ELA GOLD HOUSE AND MEGA MARTS';
UPDATE customers SET phone='0773702740', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='S.A.FASHION';
UPDATE customers SET phone='0770855108', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='METRO FANCY';
UPDATE customers SET phone='0774040094', area='HALI-ELA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='GOLDEN FASHION';
UPDATE customers SET phone='0783545128', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='CHAMASHAA TREDE CENTER';
UPDATE customers SET phone='0770396911', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='INDIYAN CELECTION';
UPDATE customers SET phone='0778545122', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='BAWA TEXTILE';
UPDATE customers SET phone='0774986409', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FASHION CITY';
UPDATE customers SET phone='0765626445', area='HAPUTALE', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='LOVERS';
UPDATE customers SET phone='0572268618', area='HAPUTALE', tier='Bronze', shop_type='Multi Outlet' WHERE name='UPUL TREDE CENTER';
UPDATE customers SET phone='0724659483', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='KALAIMAGAL FANCY HOUSE';
UPDATE customers SET phone='0575671170', area='HAPUTALE', tier='Silver', shop_type='Textile and Fashion' WHERE name='LIBAS TEX';
UPDATE customers SET phone='0552235425', area='HAPUTALE', tier='Emergency Top-up', shop_type='Multi Outlet' WHERE name='GAYATHTRI FANCY';
UPDATE customers SET phone='0572268077', area='HAPUTALE', tier='Silver', shop_type='Textile and Fashion' WHERE name='SRI NANDANA TEX';
UPDATE customers SET phone='0777410185', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SUGUNAS';
UPDATE customers SET phone='0775623142', area='HAPUTALE', tier='Silver', shop_type='Textile and Fashion' WHERE name='SARAWENAS TEXTAILE';
UPDATE customers SET phone='0773417033', area='HAPUTALE', tier='Silver', shop_type='Shoe Shop' WHERE name='KAARAAS SHOE CENTER';
UPDATE customers SET phone='0777918696', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='THE PEARL SELECTION';
UPDATE customers SET phone='0775500431', area='HAPUTALE', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='SRI LUCK FANCY';
UPDATE customers SET phone='0552234125', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='BAWA FANCY';
UPDATE customers SET phone='0773545215', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='KRISHNA UVA FANCY';
UPDATE customers SET phone='0572245328', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SANGEETHA TEXTILE';
UPDATE customers SET phone='0773542135', area='HAPUTALE', tier='Silver', shop_type='Textile and Fashion' WHERE name='PARAHAN TEXTILE';
UPDATE customers SET phone='0770551741', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='S.S.LOVERS';
UPDATE customers SET phone='0754530353', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='K.G.O.THISSA';
UPDATE customers SET phone='0768399929', area='HAPUTALE', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MAHAJANA FANCY';
UPDATE customers SET phone='0572268644', area='HAPUTALE', tier='Emergency Top-up', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW RUSSI FANCY MAHAL';
UPDATE customers SET phone='0785002546', area='HAPUTALE', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='YASHELI LOVER AND SHOE PALACE';
UPDATE customers SET phone='0783931390', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='K.G.SANCHALA';
UPDATE customers SET phone='0782958191', area='HAPUTALE', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='SUWADARATHI';
UPDATE customers SET phone='0778087071', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='DILA MULTI SHOP';
UPDATE customers SET phone='0713911216', area='HAPUTALE', tier='Silver', shop_type='Grocery' WHERE name='NEW THAKSALA STORES';
UPDATE customers SET phone='0764857542', area='HAPUTALE', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHARA FASHION';
UPDATE customers SET phone='0779279846', area='HAPUTALE', tier='Bronze', shop_type='Multi Outlet' WHERE name='AYESHA LOVERS';
UPDATE customers SET phone='0722088065', area='HAPUTALE', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SUSA DENIM KADE';
UPDATE customers SET phone='0775099868', area='HAPUTALE', tier='Silver', shop_type='Textile and Fashion' WHERE name='SHALINI TEX';
UPDATE customers SET phone='0775798848', area='HAPUTALE', tier='Platinum', shop_type='Fancy Outlet' WHERE name='NEW AUM CENTER';
UPDATE customers SET phone='0716620542', area='LUNUGALA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='PRIYANGA ELECTRICALS';
UPDATE customers SET phone='0772669816', area='LUNUGALA', tier='Silver', shop_type='Multi Outlet' WHERE name='MADUKA TREDE CENTER';
UPDATE customers SET phone='0769155903', area='LUNUGALA', tier='Silver', shop_type='Multi Outlet' WHERE name='FHAHEEM';
UPDATE customers SET phone='0767475758', area='LUNUGALA', tier='Silver', shop_type='Textile and Fashion' WHERE name='CHRISTER FASHION';
UPDATE customers SET phone='0767117280', area='LUNUGALA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SIDHEEQ STORES';
UPDATE customers SET phone='0778103957', area='LUNUGALA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='ROY FASHION';
UPDATE customers SET phone='0785625145', area='LUNUGALA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='J FASHION';
UPDATE customers SET phone='0773762001', area='LUNUGALA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='SUN TEX';
UPDATE customers SET phone='N/A', area='LUNUGALA', tier='Bronze', shop_type='Grocery' WHERE name='KOGUL STORES';
UPDATE customers SET phone='0750739474', area='LUNUGALA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='FANCY BAZAAR';
UPDATE customers SET phone='0767463346', area='LUNUGALA', tier='Bronze', shop_type='Grocery' WHERE name='RILWAN STORES';
UPDATE customers SET phone='0766573645', area='LUNUGALA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='KRISHANI FASHION';
UPDATE customers SET phone='0775614400', area='LUNUGALA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHARA FASHION';
UPDATE customers SET phone='0715223739', area='LUNUGALA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='CHANDI';
UPDATE customers SET phone='0767871778', area='LUNUGALA', tier='Bronze', shop_type='Grocery' WHERE name='VINAYAGA FOOD CITY';
UPDATE customers SET phone='0703908988', area='MEEGAHAKIULA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='NIMSHARA FASHION';
UPDATE customers SET phone='0779501784', area='MEEGAHAKIULA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='HIMASHI BOOK SHOP';
UPDATE customers SET phone='0773904941', area='MEEGAHAKIULA', tier='Silver', shop_type='Super Market' WHERE name='RATHNA SUPER CITY';
UPDATE customers SET phone='0773904941', area='MEEGAHAKIULA', tier='Silver', shop_type='Super Market' WHERE name='RATHNAYAKA STORE';
UPDATE customers SET phone='0775635187', area='MEEGAHAKIULA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NALIN FASHION';
UPDATE customers SET phone='0783825178', area='MEEGAHAKIULA', tier='Platinum', shop_type='Bag Shop' WHERE name='HELASITH TAILORS';
UPDATE customers SET phone='0773625485', area='MEEGAHAKIULA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='THAWINDU BOOK SHOP';
UPDATE customers SET phone='0786545128', area='MEEGAHAKIULA', tier='Gold', shop_type='Grocery' WHERE name='BADULLA TAILORS';
UPDATE customers SET phone='0778541210', area='MEEGAHAKIULA', tier='Bronze', shop_type='Grocery' WHERE name='RAJA STORE';
UPDATE customers SET phone='0786501210', area='MEEGAHAKIULA', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='SAMADHI POOJA';
UPDATE customers SET phone='0775425353', area='MEEGAHAKIULA', tier='Bronze', shop_type='Grocery' WHERE name='CHANDANA VIDEO ANDCOMIUNICATION';
UPDATE customers SET phone='0778380402', area='MEEGAHAKIULA', tier='Silver', shop_type='Multi Outlet' WHERE name='KALPE SALES CENTER';
UPDATE customers SET phone='0777280871', area='MEEGAHAKIULA', tier='Silver', shop_type='Multi Outlet' WHERE name='CENTRAL TRADING';
UPDATE customers SET phone='0775623125', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='TOP SELECTION';
UPDATE customers SET phone='0760776414', area='MAHIYANGANAYA 01', tier='Emergency Top-up', shop_type='Hospitals' WHERE name='SUBASADANA APANA SHALAWA';
UPDATE customers SET phone='0552257572', area='MAHIYANGANAYA 01', tier='Gold', shop_type='Multi Outlet' WHERE name='JAYANANDANA TRADE CENTER';
UPDATE customers SET phone='0762093393', area='MAHIYANGANAYA 01', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='DEDUNU LOVERS';
UPDATE customers SET phone='0775341010', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='IDUSARA TEX';
UPDATE customers SET phone='0760155847', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='VEENAS TEX';
UPDATE customers SET phone='0769104515', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='NEW  WISMI TEXTILE';
UPDATE customers SET phone='0776404898', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MALSHA FASHION';
UPDATE customers SET phone='0776085557', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='DASUN LANKA CURTAIN HOUSE';
UPDATE customers SET phone='0711237708', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHAVINDI TEXTILE';
UPDATE customers SET phone='0770842369', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='DINUSHA FASHION';
UPDATE customers SET phone='0715522350', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='DISNY';
UPDATE customers SET phone='0785622357', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FASHION TEX';
UPDATE customers SET phone='0776148922', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Hotels and Restaurants' WHERE name='MAHAJANA APANA SHALAWA';
UPDATE customers SET phone='0702778115', area='MAHIYANGANAYA 01', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='E.A.M.MALIBAN GARMENT';
UPDATE customers SET phone='0774534468', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Shoe Shop' WHERE name='GEM LIGHT SHOE PALECE';
UPDATE customers SET phone='0552258265', area='MAHIYANGANAYA 01', tier='Platinum', shop_type='Shoe Shop' WHERE name='STAR SHOE PALACE';
UPDATE customers SET phone='0784525125', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='MUTHUGALA POOJA BANDA';
UPDATE customers SET phone='0715451393', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='PRIMARK';
UPDATE customers SET phone='0715522350', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW SHARMILA FASHION';
UPDATE customers SET phone='0763548158', area='MAHIYANGANAYA 01', tier='Emergency Top-up', shop_type='Shoe Shop' WHERE name='NALIN SHOE';
UPDATE customers SET phone='0552257123', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Multi Outlet' WHERE name='SIRI JAYAMINI STORES';
UPDATE customers SET phone='0775635187', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='NALIN FASHION';
UPDATE customers SET phone='0777731125', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='FANCY PALACE';
UPDATE customers SET phone='0777224366', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='MALSIRI STORES';
UPDATE customers SET phone='0774524150', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='TOP TEX';
UPDATE customers SET phone='0778541210', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Grocery' WHERE name='RAJA STORE';
UPDATE customers SET phone='0786501210', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='SAMADHI POOJA';
UPDATE customers SET phone='0786545120', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='LAND MARK';
UPDATE customers SET phone='0715881679', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='AJANTHA TRADE CENTER';
UPDATE customers SET phone='0778813696', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW NIPPON TREDERS';
UPDATE customers SET phone='0760437261', area='MAHIYANGANAYA 01', tier='Emergency Top-up', shop_type='Cosmetic and Fancy Outlet' WHERE name='MULTI PALAZAA';
UPDATE customers SET phone='0775754300', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='VILASITHA TEXTILE';
UPDATE customers SET phone='0771362900', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='BADDEGAME STORES';
UPDATE customers SET phone='0773147765', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='MALI GIFT';
UPDATE customers SET phone='0714912510', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='RANDILU FASHION';
UPDATE customers SET phone='0775425353', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Grocery' WHERE name='CHANDANA VIDEO ANDCOMIUNICATION';
UPDATE customers SET phone='0760753682', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Shoe Shop' WHERE name='MOD SHOE';
UPDATE customers SET phone='0777887249', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Multi Outlet' WHERE name='CITY LOVER';
UPDATE customers SET phone='0724900614', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='HESHAN TEX';
UPDATE customers SET phone='0767810105', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='JAYANTHA TAILORS';
UPDATE customers SET phone='0552256149', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='W.K.GROCERY';
UPDATE customers SET phone='0772342615', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Multi Outlet' WHERE name='NEW KASUN PLAZA';
UPDATE customers SET phone='0764553840', area='MAHIYANGANAYA 01', tier='Bronze', shop_type='Textile and Fashion' WHERE name='GIMSARA TEX';
UPDATE customers SET phone='0776935193', area='MAHIYANGANAYA 01', tier='Gold', shop_type='Book Shop and Communication' WHERE name='PUSHPAKUMARA BOOK SHOP';
UPDATE customers SET phone='0777523123', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='purple Park textile';
UPDATE customers SET phone='0771000882', area='MAHIYANGANAYA 01', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='LEON';
UPDATE customers SET phone='0770503088', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Textile and Fashion' WHERE name='BIG FASHION';
UPDATE customers SET phone='0761444034', area='MAHIYANGANAYA 01', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='UK FASHION';
UPDATE customers SET phone='0769857573', area='MAHIYANGANAYA 01', tier='Gold', shop_type='Multi Outlet' WHERE name='KANDURATA SOFA';
UPDATE customers SET phone='0775624135', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='RATHNAKUMARA';
UPDATE customers SET phone='0773200360', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MADAWA TEX';
UPDATE customers SET phone='0552257776', area='MAHIYANGANAYA 02', tier='Silver', shop_type='Multi Outlet' WHERE name='GEETHA TRADE CENTER';
UPDATE customers SET phone='0775625142', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MIHINDU TEXTILE';
UPDATE customers SET phone='0552257432', area='MAHIYANGANAYA 02', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='HASSALAKA CAMICALS';
UPDATE customers SET phone='0552257094', area='MAHIYANGANAYA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='SENEVIRATHNA TRADE CENTER';
UPDATE customers SET phone='0775612369', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MAN GET TEXTILE';
UPDATE customers SET phone='0773000590', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Multi Outlet' WHERE name='NIMALI BOOK SHOP';
UPDATE customers SET phone='0784525125', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Pooja Banda Outlet' WHERE name='MUTHUGALA POOJA BANDA';
UPDATE customers SET phone='0773662228', area='MAHIYANGANAYA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='WIJERATHNA STORES';
UPDATE customers SET phone='0552257189', area='MAHIYANGANAYA 02', tier='Bronze', shop_type='Multi Outlet' WHERE name='RATHNA TRADERS';
UPDATE customers SET phone='0715538338', area='MAHIYANGANAYA 02', tier='Silver', shop_type='Textile and Fashion' WHERE name='VILASITHA';
UPDATE customers SET phone='0742207479', area='MAHIYANGANAYA 02', tier='Silver', shop_type='Fancy Outlet' WHERE name='ORINSAL';
UPDATE customers SET phone='0767709952', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='MUKSITH FANCY';
UPDATE customers SET phone='0751232658', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='FANCY MAHAL';
UPDATE customers SET phone='0772804400', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='LAKSHMI FANCY';
UPDATE customers SET phone='0771602109', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='ROYAL FANCY';
UPDATE customers SET phone='0554562523', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='VIJI FANCY SHOP';
UPDATE customers SET phone='0706512458', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='MOOMINS';
UPDATE customers SET phone='0770741623', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SAVEENA FASHION';
UPDATE customers SET phone='0777139922', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='FIRST CHOICE';
UPDATE customers SET phone='0763668116', area='PASSARA', tier='Gold', shop_type='Shoe Shop' WHERE name='RIVINDU SHOE PALACE';
UPDATE customers SET phone='0767468121', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SANDALU RATHNAYAKA';
UPDATE customers SET phone='0723695047', area='PASSARA', tier='Silver', shop_type='Textile and Fashion' WHERE name='RATHNAYAKA TEXTILES';
UPDATE customers SET phone='0777005753', area='PASSARA', tier='Silver', shop_type='Textile and Fashion' WHERE name='NEW CELEBRATION';
UPDATE customers SET phone='0775645123', area='PASSARA', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='ARALIYA TEX';
UPDATE customers SET phone='0778956125', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='RAMESH TEX';
UPDATE customers SET phone='0785623124', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='BEUTY LOVERS';
UPDATE customers SET phone='0779418181', area='PASSARA', tier='Gold', shop_type='Cosmetic and Fancy Outlet' WHERE name='STAR FANCY';
UPDATE customers SET phone='0552288591', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW FASKINS';
UPDATE customers SET phone='0781648302', area='PASSARA', tier='Bronze', shop_type='Multi Outlet' WHERE name='LULU';
UPDATE customers SET phone='0715112264', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='CROWN BOOK SHOP';
UPDATE customers SET phone='0772136999', area='PASSARA', tier='Silver', shop_type='Textile and Fashion' WHERE name='AROMAA FASHION';
UPDATE customers SET phone='0552288388', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='NADEEKA ENTERPRISES';
UPDATE customers SET phone='0552288013', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FARSHANS TEXTILE';
UPDATE customers SET phone='0777076594', area='PASSARA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW FARSHANS FANCY HOUSE';
UPDATE customers SET phone='0552288468', area='PASSARA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='NEW MANISHARAS FANCY';
UPDATE customers SET phone='0777882020', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='JABBAR TEX';
UPDATE customers SET phone='0718557895', area='PASSARA', tier='Bronze', shop_type='Multi Outlet' WHERE name='SK FANCY';
UPDATE customers SET phone='0767382812', area='PASSARA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='FATHMA FANCY';
UPDATE customers SET phone='0770859207', area='PASSARA', tier='Silver', shop_type='Shoe Shop' WHERE name='BAAI SHOE';
UPDATE customers SET phone='0763668116', area='PASSARA', tier='Silver', shop_type='Shoe Shop' WHERE name='P.B.I. SHOE';
UPDATE customers SET phone='0719211892', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='GIVINDI TEXTILE';
UPDATE customers SET phone='0755135751', area='PASSARA', tier='Silver', shop_type='Textile and Fashion' WHERE name='SALE WEEK';
UPDATE customers SET phone='0702221817', area='PASSARA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='DENU KIDS MART';
UPDATE customers SET phone='0778925982', area='PASSARA', tier='Bronze', shop_type='Multi Outlet' WHERE name='THIHE KADE';
UPDATE customers SET phone='N/A', area='PASSARA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='YNUS TEX';
UPDATE customers SET phone='0763610036', area='PASSARA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='RISHANA BOOK SHOP';
UPDATE customers SET phone='0764567432', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='SATTHAR';
UPDATE customers SET phone='0777122477', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='DRESS MART';
UPDATE customers SET phone='0773229253', area='WELIMADA', tier='Bronze', shop_type='Shoe Shop' WHERE name='PIYAWARA PAWAHAN MANDIRAYA';
UPDATE customers SET phone='0572245601', area='WELIMADA', tier='Gold', shop_type='Shoe Shop' WHERE name='NEW GIFT SHOE PALACE';
UPDATE customers SET phone='0572245012', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='NEW ARIYA STORES';
UPDATE customers SET phone='0777426717', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='UNLIMIT';
UPDATE customers SET phone='0750148948', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='JEMILAS TEX';
UPDATE customers SET phone='0552245040', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='REBOND';
UPDATE customers SET phone='0760101712', area='WELIMADA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='NADEE BOOK SHOP';
UPDATE customers SET phone='0775941080', area='WELIMADA', tier='Gold', shop_type='Textile and Fashion' WHERE name='NEW SATTAR';
UPDATE customers SET phone='0768582243', area='WELIMADA', tier='Gold', shop_type='Shoe Shop' WHERE name='FASHION SHOE PALACE';
UPDATE customers SET phone='0777959480', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FASHION CITY';
UPDATE customers SET phone='0572245699', area='WELIMADA', tier='Emergency Top-up', shop_type='Other Outlet' WHERE name='LEWIS AND SONS';
UPDATE customers SET phone='0779683344', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='MINNA CUT PEASES';
UPDATE customers SET phone='0572245327', area='WELIMADA', tier='Gold', shop_type='Textile and Fashion' WHERE name='KADURATA CHOICE';
UPDATE customers SET phone='0723670706', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='BEAUTY FASHION';
UPDATE customers SET phone='0757331620', area='WELIMADA', tier='Silver', shop_type='Grocery' WHERE name='MADUSHANI SHOE MART';
UPDATE customers SET phone='0552294081', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='DHARSHANA TEXTILE';
UPDATE customers SET phone='0718154246', area='WELIMADA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='JAYANI MULTI SHOP';
UPDATE customers SET phone='0718179753', area='WELIMADA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='NAYANA BOOK SHOP';
UPDATE customers SET phone='0767999090', area='WELIMADA', tier='Silver', shop_type='Shoe Shop' WHERE name='RIZLAN SHOE';
UPDATE customers SET phone='0770307240', area='WELIMADA', tier='Emergency Top-up', shop_type='Cosmetic and Fancy Outlet' WHERE name='WELIMADA CHEEP SIDE';
UPDATE customers SET phone='0776263635', area='WELIMADA', tier='Silver', shop_type='Pooja Banda Outlet' WHERE name='GHANDHARYA POOJA BANDA';
UPDATE customers SET phone='0772379537', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='ARADENA TEXTILE';
UPDATE customers SET phone='0785645128', area='WELIMADA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='HANA TRADING';
UPDATE customers SET phone='0774469188', area='WELIMADA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='HELLOW BABY';
UPDATE customers SET phone='0777349652', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SHAN FASHION';
UPDATE customers SET phone='0776311413', area='WELIMADA', tier='Emergency Top-up', shop_type='Textile and Fashion' WHERE name='ISHARA FASHION';
UPDATE customers SET phone='0769802787', area='WELIMADA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='GODAKUMBURA BOOK SHOP';
UPDATE customers SET phone='0777100477', area='WELIMADA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='BABY CHOICE';
UPDATE customers SET phone='0773229253', area='WELIMADA', tier='Bronze', shop_type='Shoe Shop' WHERE name='PIYAWARA SHOE PALACE';
UPDATE customers SET phone='0718232926', area='WELIMADA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='JEMINI POSILEN';
UPDATE customers SET phone='0716223131', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='D.B.R. Tex';
UPDATE customers SET phone='0777814804', area='WELIMADA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='YOGAS FANCY SHOP';
UPDATE customers SET phone='0774679200', area='WELIMADA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='BEST BUY';
UPDATE customers SET phone='0777214735', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='LEELA TRADERS';
UPDATE customers SET phone='0779874129', area='WELIMADA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='ASIAN LANKA';
UPDATE customers SET phone='0773229253', area='WELIMADA', tier='Emergency Top-up', shop_type='Multi Outlet' WHERE name='PIYAPATH SEWANA';
UPDATE customers SET phone='0770111101', area='WELIMADA', tier='Emergency Top-up', shop_type='Grocery' WHERE name='SANDALU TREDE CENTER';
UPDATE customers SET phone='0552295036', area='WELIMADA', tier='Bronze', shop_type='Grocery' WHERE name='GALLEGE STORES';
UPDATE customers SET phone='0765669211', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='FASHION DRESS';
UPDATE customers SET phone='0752373339', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='ASHIK FANCY';
UPDATE customers SET phone='0770111101', area='WELIMADA', tier='Emergency Top-up', shop_type='Super Market' WHERE name='SADALU SUPER CENTRE';
UPDATE customers SET phone='0767150150', area='WELIMADA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='VICRICK MULTI SHOP';
UPDATE customers SET phone='0766769909', area='WELIMADA', tier='Silver', shop_type='Cosmetic and Fancy Outlet' WHERE name='ANAS FANCY';
UPDATE customers SET phone='0763300578', area='WELIMADA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='BABY COTTON CARE';
UPDATE customers SET phone='0719846101', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='HINASHA MULTI SHOP';
UPDATE customers SET phone='0767121443', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='NILUM';
UPDATE customers SET phone='0754718085', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='YUSUF SALES CENTER';
UPDATE customers SET phone='0767982667', area='WELIMADA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='AITRA LINK';
UPDATE customers SET phone='0775806240', area='WELIMADA', tier='Bronze', shop_type='Cosmetic and Fancy Outlet' WHERE name='BOMBAY BAZAAR';
UPDATE customers SET phone='0717914116', area='WELIMADA', tier='Silver', shop_type='Textile and Fashion' WHERE name='GIHAN FASHION';
UPDATE customers SET phone='0726935313', area='WELIMADA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='DISANDI BABY SHOP';
UPDATE customers SET phone='0701756865', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='SUMUDU TEXTILE';
UPDATE customers SET phone='0711125093', area='WELIMADA', tier='Bronze', shop_type='Book Shop and Communication' WHERE name='THUSHARA BOOK SHOP';
UPDATE customers SET phone='0764853248', area='WELIMADA', tier='Silver', shop_type='Book Shop and Communication' WHERE name='RATHNA TALERS AND BOOK SHOP';
UPDATE customers SET phone='0727453947', area='WELIMADA', tier='Bronze', shop_type='Mother/Baby Care Outlet' WHERE name='JESHAN FASHION';
UPDATE customers SET phone='0572247131', area='WELIMADA', tier='Bronze', shop_type='Textile and Fashion' WHERE name='B.M.S. SALE CENTER';
UPDATE customers SET phone='0775559559', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='GEMINI ELECTRICALS';
UPDATE customers SET phone='0769125003', area='WELIMADA', tier='Bronze', shop_type='Grocery' WHERE name='HAPPY CHOICES';
UPDATE customers SET phone='0758550856', area='WELIMADA', tier='Bronze', shop_type='Fancy Outlet' WHERE name='VL MULTI LAND';
UPDATE customers SET phone='0773133531', area='WELIMADA', tier='Bronze', shop_type='Multi Outlet' WHERE name='JAYASIRI MULTY SHOP';
UPDATE customers SET phone='0778050797', area='WELIMADA', tier='Bronze', shop_type='Fancy Outlet' WHERE name='GL GLAM LANKA';
