-- Remove bill_return_items referencing the duplicate products before deleting them
DELETE FROM bill_return_items
WHERE product_id IN (
  SELECT id FROM return_products
  WHERE business = 'RAINCO'
    AND name IN (
      'CP1020-Printed Polyester-2F-Steel Frame',
      'CP1040-Printed Polyester-2F-Steel Frame',
      'CP1041-Black Polyester-2F-Steel Frame-Cu',
      'CP1042-Maroon Polyester-2F-Steel Frame-C',
      'CP1044-Yellow Polyester-2F-Steel Frame-C',
      'CP1046-Silver Coated Polyester-2F-Steel',
      'CP1047-Printed Satin-2F-Steel Frame',
      'CP1070-Printed Polyester-3F-Steel Frame',
      'CP1071-Silver Coated Nylon-3F-Steel Fra',
      'CP1075-Black Polyester-3F-Steel Frame',
      'CP1076-Silver Coated Polyester-3F-Steel',
      'CP1077-Printed Satin-3F-Steel Frame',
      'CP1090-Nano-Solid Colour Pongee-3F-Steel',
      'CP1146-Silver Coated Black Polyester-2F-',
      'CP11600-Kids-Luminous Polyester-Steel Fr',
      'CP1160-Kids-Printed Polyester-Steel Fram',
      'CP1440-Printed Polyester-Frill-2F-Steel',
      'CP1470-Printed Polyester-Frill-3F-Steel',
      'CP1778-Sun proof collection - 2018 Mater',
      'CP2501-Black Polyester-Steel Frame-Curve',
      'CP2502-Maroon Polyester-Steel Frame-Cu',
      'CP2504-Yellow Polyester-Steel Frame-Cur',
      'CP2563-Multi Colour Polyester-24-Steel',
      'CP2571-Black Polyester-27-Steel Frame',
      'CP2573-Multi Colour Polyester-27Steel Fr',
      'CP2583-Multi Colour Polyester-30-Steel',
      'CP2584-Muthu Kuda-Plain Yellow Polyester',
      'CP3830-Golden Bed Net-Single',
      'CP3831-Golden Bed Net-Double',
      'CP3832-Golden Bed Net-Queen',
      'CP3833-Golden Bed Net-King',
      'CP3890-Pearl Bed Net-Single',
      'CP3891-Pearl Bed Net-Double',
      'CP3892-Pearl Bed Net-Queen',
      'CP3893-Pearl Bed Net-King-California Ki',
      'CP3910-Singithi Baby Plain',
      'CP3912-Singithi Toddler Plain',
      'CP3913-Singithi Baby Printed',
      'CP4768-Multi Colour Oxford-40-Steel Fra',
      'CP5020-Super Force-Rain Coat-Small',
      'CP5021-Super Force-Rain Coat-Medium',
      'CP5022-Super Force-Rain Coat-Large',
      'CP5023-Super Force-Rain Coat-Extra Large',
      'CP5050-Super Force-Rain Suit-Two Pcs-Sma',
      'CP5051-Super Force-Rain Suit-Two Pcs-Med',
      'CP5052-Super Force-Rain Suit-Two Pcs-Lar',
      'CP5053-Super Force-Rain Suit-Two Pcs-Ext',
      'CPJ6050-JUNIOR RAINCOAT SMALL',
      'CPJ6051-JUNIOR RAINCOAT MEDIUM',
      'CPJ6052-JUNIOR RAINCOAT LARGE',
      'CPJ6053-JUNIOR RAINCOAT EXTRA LARGE',
      'CPTM1644-1640 FRAME WITH PONGEE FABRIC',
      'CPTM1771-1770 FRAME WITH NYLON SILVER FA',
      'CPTM2673-FRP FRAME WITH PONGEE-27',
      'P1020-Printed Polyester-2F-Steel Frame',
      'P1040-Printed Polyester-2F-Steel Frame'
    )
);

-- Remove CP-prefixed entries that are exact price duplicates of their plain counterparts
DELETE FROM return_products
WHERE business = 'RAINCO'
  AND name IN (
    -- CP vs plain (same price)
    'CP1020-Printed Polyester-2F-Steel Frame',
    'CP1040-Printed Polyester-2F-Steel Frame',
    'CP1041-Black Polyester-2F-Steel Frame-Cu',
    'CP1042-Maroon Polyester-2F-Steel Frame-C',
    'CP1044-Yellow Polyester-2F-Steel Frame-C',
    'CP1046-Silver Coated Polyester-2F-Steel',
    'CP1047-Printed Satin-2F-Steel Frame',
    'CP1070-Printed Polyester-3F-Steel Frame',
    'CP1071-Silver Coated Nylon-3F-Steel Fra',
    'CP1075-Black Polyester-3F-Steel Frame',
    'CP1076-Silver Coated Polyester-3F-Steel',
    'CP1077-Printed Satin-3F-Steel Frame',
    'CP1090-Nano-Solid Colour Pongee-3F-Steel',
    'CP1146-Silver Coated Black Polyester-2F-',
    'CP11600-Kids-Luminous Polyester-Steel Fr',
    'CP1160-Kids-Printed Polyester-Steel Fram',
    'CP1440-Printed Polyester-Frill-2F-Steel',
    'CP1470-Printed Polyester-Frill-3F-Steel',
    'CP1778-Sun proof collection - 2018 Mater',
    'CP2501-Black Polyester-Steel Frame-Curve',
    'CP2502-Maroon Polyester-Steel Frame-Cu',
    'CP2504-Yellow Polyester-Steel Frame-Cur',
    'CP2563-Multi Colour Polyester-24-Steel',
    'CP2571-Black Polyester-27-Steel Frame',
    'CP2573-Multi Colour Polyester-27Steel Fr',
    'CP2583-Multi Colour Polyester-30-Steel',
    'CP2584-Muthu Kuda-Plain Yellow Polyester',
    'CP3830-Golden Bed Net-Single',
    'CP3831-Golden Bed Net-Double',
    'CP3832-Golden Bed Net-Queen',
    'CP3833-Golden Bed Net-King',
    'CP3890-Pearl Bed Net-Single',
    'CP3891-Pearl Bed Net-Double',
    'CP3892-Pearl Bed Net-Queen',
    'CP3893-Pearl Bed Net-King-California Ki',
    'CP3910-Singithi Baby Plain',
    'CP3912-Singithi Toddler Plain',
    'CP3913-Singithi Baby Printed',
    'CP4768-Multi Colour Oxford-40-Steel Fra',
    'CP5020-Super Force-Rain Coat-Small',
    'CP5021-Super Force-Rain Coat-Medium',
    'CP5022-Super Force-Rain Coat-Large',
    'CP5023-Super Force-Rain Coat-Extra Large',
    'CP5050-Super Force-Rain Suit-Two Pcs-Sma',
    'CP5051-Super Force-Rain Suit-Two Pcs-Med',
    'CP5052-Super Force-Rain Suit-Two Pcs-Lar',
    'CP5053-Super Force-Rain Suit-Two Pcs-Ext',
    -- CPJ vs J (same price)
    'CPJ6050-JUNIOR RAINCOAT SMALL',
    'CPJ6051-JUNIOR RAINCOAT MEDIUM',
    'CPJ6052-JUNIOR RAINCOAT LARGE',
    'CPJ6053-JUNIOR RAINCOAT EXTRA LARGE',
    -- CPTM vs TM (same price)
    'CPTM1644-1640 FRAME WITH PONGEE FABRIC',
    'CPTM1771-1770 FRAME WITH NYLON SILVER FA',
    'CPTM2673-FRP FRAME WITH PONGEE-27',
    -- P vs plain (same price)
    'P1020-Printed Polyester-2F-Steel Frame',
    -- P vs plain (different price, removed on request)
    'P1040-Printed Polyester-2F-Steel Frame'
  );
