spring:
  application:
    name: finance

  datasource:
    url: jdbc:postgresql://ep-aged-tree-ao5ii011-pooler.c-2.ap-southeast-1.aws.neon.tech/ghanim_db?sslmode=require&channelBinding=require
    username: ghanim_user
    password: Ghanimpostgres@5176
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: k8f9$Lm2#pQx7vR!sTz4Yw9@C6nE1hJdUoP5aB3XgHqL0ZrM
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG


